name = "tauri-update-server"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[vars]
GITHUB_ACCOUNT = 'BlackRedSolutionsTeam'
GITHUB_REPO = 'delybox-desktop-app'
