name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: ${{ secrets.GITHUB_API_TOKEN != '' && 'GITHUB_API_TOKEN' || '' }}
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
